# Generated by Django 4.2.11 on 2024-04-05 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_alter_personfilmwork_film_work'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personfilmwork',
            name='film_work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='persons', to='movies.filmwork', verbose_name='Film work'),
        ),
    ]
