# Generated by Django 4.2.11 on 2024-03-23 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_alter_filmwork_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genrefilmwork',
            name='modified',
        ),
        migrations.AddField(
            model_name='filmwork',
            name='genres',
            field=models.ManyToManyField(related_name='film_works', through='movies.GenreFilmWork', to='movies.genre'),
        ),
    ]
