# Generated by Django 4.2.11 on 2024-03-23 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_remove_genrefilmwork_modified_filmwork_genres'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personfilmwork',
            name='modified',
        ),
    ]
